package crypto

// CryptoKeysAndAddress represents an address key pair generated by calling following methods:
// - GenerateCryptoKeysAndAddressByRootSeeds
// - GenerateCryptoKeysAndAddressByRandSeeds
// - GenerateCryptoKeysAndAddressByRootSeedsFromPublicRand
// in where, DetectorKey is added for new types of address
type CryptoKeysAndAddress struct {
	SpendSecretKey    []byte
	SerialNoSecretKey []byte
	ViewSecretKey     []byte
	DetectorKey       []byte // added with version 2
	CryptoAddress     *CryptoAddress
}
